# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7f4573112756fbd1aca76dd7c77f191da63a9bad649b8ea6036e3abbb2bacbf508cad23c73fcee8bd201f8c5f8c28628fd6ad279cd05856a9ef6295887a9960

test:
  secret_key_base: 6728e27a26d685dcf2e2a1e4926a2b3ab806d76c392d0bdd161888320d153d14de4e5252901ebaacd00ce9d522c8b74636a2f9a1f6c2398bec0b075f15900c5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
